export const googleFonts: string[] = [
  'Anton',
  'Arial',
  'Bebas Neue',
  'Dancing Script',
  'Inconsolata',
  'Inter',
  'Lato',
  'Lobster',
  'Merriweather',
  'Montserrat',
  'Mukta',
  'Nunito',
  'Open Sans',
  'Oswald',
  'PT Sans',
  'Playfair Display',
  'Poppins',
  'Quicksand',
  'Raleway',
  'Righteous',
  'Roboto',
  'Roboto Slab',
  'Rubik',
  'Ubuntu',
];
