import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { FontProvider } from 'react-dynamic-fonts';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className=''>
        <FontProvider
          defaultFont='Inter'
          fonts={['Inter', 'Lato', 'Montserrat', 'Raleway', 'Poppins']}>
          {children}
        </FontProvider>
      </body>
    </html>
  );
}
